export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAIL = "SEARCH_BOOKS_FAIL";
export const SEARCH_BOOKS_RESET = "SEARCH_BOOKS_RESET";
